type Admin {
    id: ID!
    username: String!
    fullname: String!
    birthDate: Date!
    phone: String!
    tgUsername: String!
    isActive: Boolean!
    createdAt: Date!
}

type Query {
    getAdmins:[Admin!]!
}