type LoginResponse {
  success: Boolean!
  message: String
  token: String
}
type Mutation {
  login(username: String!, password: String!, userType:String!): LoginResponse!
}
type Query {
  me: Boolean!
}