type Root {
    id: ID!
    username: String!
    fullname: String!
    createdAt: Date!
}

type Mutation {
    addAdmin(
        username: String!
        password: String!
        fullname: String!
        tgUsername: String!
        birthDate: Date!
        phone: Phone!
    ): Admin!
}