type Teacher {
    id: ID!
    username: String!
    fullname: String!
    birthDate: Date!
    phone: String!
    tgUsername: String!
    department: String!
    isActive: Boolean!
    createdAt: Date!
}

type Query {
    getTeachers: [Teacher!]!
    getTeacher(id: ID!): Teacher
}

type Mutation {
    addTeacher(
        username: String!
        password: String!
        fullname: String!
        tgUsername: String!
        birthDate: Date!
        phone: Phone!
        department: String!
    ): Teacher!
    
    changeTeacher(
        id: ID!
        username: String
        fullname: String
        birthDate: Date
        phone: Phone
        tgUsername: String
        password: String
        isActive: Boolean
    ): Teacher!
}
